project:
  type: book
  preview:
    port: 1234
    browser: false

book:
  title: "Statistical Rethinking"
  author: "Michal Lauer"
  date: today
  chapters:
    - index.qmd
    - ch02.qmd
    - ch03.qmd
    - ch04.qmd

format:
  html:
    theme: cosmo
    number-sections: false
    code-fold: show
    bibliography: literature.bib